export const ADD_FRIEND_SUBMIT = 'ADD_FRIEND_SUBMIT';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL';

export const ADD_GROUP_SUBMIT = 'ADD_GROUP_SUBMIT';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAIL = 'ADD_GROUP_FAIL';

export const GET_GROUPINFO_SUBMIT = 'GET_GROUPINFO_SUBMIT';
export const GET_GROUPINFO_SUCCESS = 'GET_GROUPINFO_SUCCESS';
export const GET_GROUPINFO_FAIL = 'GET_GROUPINFO_FAIL';

export const UPDATE_GROUP_SUBMIT = 'UPDATE_GROUP_SUBMIT';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';

export const GET_SELFINFO_SUBMIT = 'GET_SELFINFO_SUBMIT';
export const GET_SELFINFO_SUCCESS = 'GET_SELFINFO_SUCCESS';

export const SET_SELFINFO_SUBMIT = 'SET_SELFINFO_SUBMIT';
export const SET_SELFINFO_SUCCESS = 'SET_SELFINFO_SUCCESS';

export const LIST_GROUPS_SUBMIT = 'LIST_GROUPS_SUBMIT';
export const LIST_GROUPS_SUCCESS = 'LIST_GROUPS_SUCCESS';
export const LIST_GROUPS_FAIL = 'LIST_GROUPS_FAIL';

export const RM_GROUP_SUBMIT = 'RM_GROUP_SUBMIT';
export const RM_GROUP_SUCCESS = 'RM_GROUP_SUCCESS';
export const RM_GROUP_FAIL = 'RM_GROUP_FAIL';

export const ADD_GROUPMEMBERS_SUBMIT = 'ADD_GROUPMEMBERS_SUBMIT';
export const ADD_GROUPMEMBERS_SUCCESS = 'ADD_GROUPMEMBERS_SUCCESS';

export const RM_GROUPMEMBERS_SUBMIT = 'RM_GROUPMEMBERS_SUBMIT';
export const RM_GROUPMEMBERS_SUCCESS = 'RM_GROUPMEMBERS_SUCCESS';

export const LIST_FRIENDS_SUBMIT = 'LIST_FRIENDS_SUBMIT';
export const LIST_FRIENDS_SUCCESS = 'LIST_FRIENDS_SUCCESS';
export const LIST_FRIENDS_FAIL = 'GET_FRIENDS_SUFAIL';

export const GET_FRIENDINFO_SUBMIT = 'GET_FRIENDINFO_SUBMIT';
export const GET_FRIENDINFO_SUCCESS = 'GET_FRIENDINFO_SUCCESS';
export const GET_FRIENDINFO_FAIL = 'GET_FRIENDINFO_FAIL';

export const RM_FRIEND_SUBMIT = 'RM_FRIEND_SUBMIT';
export const RM_FRIEND_SUCCESS = 'RM_FRIEND_SUCCESS';
export const RM_FRIEND_FAIL = 'RM_FRIEND_FAIL';



